"""Add parameter_sensitivity table for Phase 3 of Task 12

Revision ID: 84403efd8a90
Revises: 97aab0116466
Create Date: 2025-10-17 03:20:00.897162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84403efd8a90'
down_revision = '97aab0116466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_sensitivity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('sensitivity_score', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('correlation_with_objective', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('importance_rank', sa.Integer(), nullable=True),
    sa.Column('mean_score', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('std_score', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('min_score', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('interactions', sa.JSON(), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'parameter_name', name='uq_parameter_sensitivity_run_param')
    )
    op.create_index('ix_parameter_sensitivity_run_importance', 'parameter_sensitivity', ['run_id', 'importance_rank'], unique=False)
    op.create_index('ix_parameter_sensitivity_run_param', 'parameter_sensitivity', ['run_id', 'parameter_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parameter_sensitivity_run_param', table_name='parameter_sensitivity')
    op.drop_index('ix_parameter_sensitivity_run_importance', table_name='parameter_sensitivity')
    op.drop_table('parameter_sensitivity')
    # ### end Alembic commands ###
