"""Add missing backtest and optimization metrics

Revision ID: a1e46e33cb22
Revises: a1b2c3d4e5f6
Create Date: 2025-10-25 19:25:42.108067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1e46e33cb22'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_violations', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_violations', 'action_taken',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_violations', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('risk_violations', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('risk_violations', 'action_taken',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'rejected'::character varying"),
               existing_nullable=False)
    op.alter_column('risk_violations', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'warning'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
